Error logging started @ 12/28/11 2:10 PM

12/28/11 2:37 PMjava.net.SocketTimeoutException: Read timed out
	at java.net.SocketInputStream.socketRead0(Native Method)
	at java.net.SocketInputStream.read(Unknown Source)
	at java.net.SocketInputStream.read(Unknown Source)
	at sun.nio.cs.StreamDecoder.readBytes(Unknown Source)
	at sun.nio.cs.StreamDecoder.implRead(Unknown Source)
	at sun.nio.cs.StreamDecoder.read(Unknown Source)
	at java.io.InputStreamReader.read(Unknown Source)
	at java.io.BufferedReader.fill(Unknown Source)
	at java.io.BufferedReader.read(Unknown Source)
	at com.suelake.habbo.net.InfoConnection.run(InfoConnection.java:166)
	at java.lang.Thread.run(Unknown Source)


12/28/11 3:03 PMjava.net.SocketTimeoutException: Read timed out
	at java.net.SocketInputStream.socketRead0(Native Method)
	at java.net.SocketInputStream.read(Unknown Source)
	at java.net.SocketInputStream.read(Unknown Source)
	at sun.nio.cs.StreamDecoder.readBytes(Unknown Source)
	at sun.nio.cs.StreamDecoder.implRead(Unknown Source)
	at sun.nio.cs.StreamDecoder.read(Unknown Source)
	at java.io.InputStreamReader.read(Unknown Source)
	at java.io.BufferedReader.fill(Unknown Source)
	at java.io.BufferedReader.read(Unknown Source)
	at com.suelake.habbo.net.InfoConnection.run(InfoConnection.java:166)
	at java.lang.Thread.run(Unknown Source)


12/28/11 3:03 PMcom.mysql.jdbc.exceptions.jdbc4.MySQLIntegrityConstraintViolationException: Duplicate entry '143-iAubree' for key 'PRIMARY'
	at sun.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
	at sun.reflect.NativeConstructorAccessorImpl.newInstance(Unknown Source)
	at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(Unknown Source)
	at java.lang.reflect.Constructor.newInstance(Unknown Source)
	at com.mysql.jdbc.Util.handleNewInstance(Util.java:406)
	at com.mysql.jdbc.Util.getInstance(Util.java:381)
	at com.mysql.jdbc.SQLError.createSQLException(SQLError.java:1015)
	at com.mysql.jdbc.SQLError.createSQLException(SQLError.java:956)
	at com.mysql.jdbc.MysqlIO.checkErrorPacket(MysqlIO.java:3515)
	at com.mysql.jdbc.MysqlIO.checkErrorPacket(MysqlIO.java:3447)
	at com.mysql.jdbc.MysqlIO.sendCommand(MysqlIO.java:1951)
	at com.mysql.jdbc.MysqlIO.sqlQueryDirect(MysqlIO.java:2101)
	at com.mysql.jdbc.ConnectionImpl.execSQL(ConnectionImpl.java:2554)
	at com.mysql.jdbc.PreparedStatement.executeInternal(PreparedStatement.java:1761)
	at com.mysql.jdbc.PreparedStatement.executeUpdate(PreparedStatement.java:2046)
	at com.mysql.jdbc.PreparedStatement.executeUpdate(PreparedStatement.java:1964)
	at com.mysql.jdbc.PreparedStatement.executeUpdate(PreparedStatement.java:1949)
	at com.suelake.habbo.users.sql.SQLUser.update(SQLUser.java:157)
	at com.blunk.storage.sql.SQLDatabase.update(SQLDatabase.java:101)
	at com.suelake.habbo.users.UserRegister.updateUser(UserRegister.java:129)
	at com.suelake.habbo.communication.CommunicationHandler.stop(CommunicationHandler.java:178)
	at com.suelake.habbo.net.InfoConnection.run(InfoConnection.java:220)
	at java.lang.Thread.run(Unknown Source)


12/28/11 3:04 PMcom.mysql.jdbc.exceptions.jdbc4.MySQLIntegrityConstraintViolationException: Duplicate entry '143-Chloe' for key 'PRIMARY'
	at sun.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
	at sun.reflect.NativeConstructorAccessorImpl.newInstance(Unknown Source)
	at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(Unknown Source)
	at java.lang.reflect.Constructor.newInstance(Unknown Source)
	at com.mysql.jdbc.Util.handleNewInstance(Util.java:406)
	at com.mysql.jdbc.Util.getInstance(Util.java:381)
	at com.mysql.jdbc.SQLError.createSQLException(SQLError.java:1015)
	at com.mysql.jdbc.SQLError.createSQLException(SQLError.java:956)
	at com.mysql.jdbc.MysqlIO.checkErrorPacket(MysqlIO.java:3515)
	at com.mysql.jdbc.MysqlIO.checkErrorPacket(MysqlIO.java:3447)
	at com.mysql.jdbc.MysqlIO.sendCommand(MysqlIO.java:1951)
	at com.mysql.jdbc.MysqlIO.sqlQueryDirect(MysqlIO.java:2101)
	at com.mysql.jdbc.ConnectionImpl.execSQL(ConnectionImpl.java:2554)
	at com.mysql.jdbc.PreparedStatement.executeInternal(PreparedStatement.java:1761)
	at com.mysql.jdbc.PreparedStatement.executeUpdate(PreparedStatement.java:2046)
	at com.mysql.jdbc.PreparedStatement.executeUpdate(PreparedStatement.java:1964)
	at com.mysql.jdbc.PreparedStatement.executeUpdate(PreparedStatement.java:1949)
	at com.suelake.habbo.users.sql.SQLUser.update(SQLUser.java:157)
	at com.blunk.storage.sql.SQLDatabase.update(SQLDatabase.java:101)
	at com.suelake.habbo.users.UserRegister.updateUser(UserRegister.java:129)
	at com.suelake.habbo.communication.CommunicationHandler.login(CommunicationHandler.java:324)
	at com.suelake.habbo.communication.requests.LOGIN.handle(LOGIN.java:16)
	at com.suelake.habbo.communication.ClientCommands.handleRequest(ClientCommands.java:360)
	at com.suelake.habbo.communication.ClientRequestHandlerManager.handleRequest(ClientRequestHandlerManager.java:23)
	at com.suelake.habbo.communication.CommunicationHandler.handleIncomingNetworkData(CommunicationHandler.java:113)
	at com.suelake.habbo.net.InfoConnection.run(InfoConnection.java:198)
	at java.lang.Thread.run(Unknown Source)


12/28/11 3:05 PMcom.mysql.jdbc.exceptions.jdbc4.MySQLIntegrityConstraintViolationException: Duplicate entry '143-Chloe' for key 'PRIMARY'
	at sun.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
	at sun.reflect.NativeConstructorAccessorImpl.newInstance(Unknown Source)
	at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(Unknown Source)
	at java.lang.reflect.Constructor.newInstance(Unknown Source)
	at com.mysql.jdbc.Util.handleNewInstance(Util.java:406)
	at com.mysql.jdbc.Util.getInstance(Util.java:381)
	at com.mysql.jdbc.SQLError.createSQLException(SQLError.java:1015)
	at com.mysql.jdbc.SQLError.createSQLException(SQLError.java:956)
	at com.mysql.jdbc.MysqlIO.checkErrorPacket(MysqlIO.java:3515)
	at com.mysql.jdbc.MysqlIO.checkErrorPacket(MysqlIO.java:3447)
	at com.mysql.jdbc.MysqlIO.sendCommand(MysqlIO.java:1951)
	at com.mysql.jdbc.MysqlIO.sqlQueryDirect(MysqlIO.java:2101)
	at com.mysql.jdbc.ConnectionImpl.execSQL(ConnectionImpl.java:2554)
	at com.mysql.jdbc.PreparedStatement.executeInternal(PreparedStatement.java:1761)
	at com.mysql.jdbc.PreparedStatement.executeUpdate(PreparedStatement.java:2046)
	at com.mysql.jdbc.PreparedStatement.executeUpdate(PreparedStatement.java:1964)
	at com.mysql.jdbc.PreparedStatement.executeUpdate(PreparedStatement.java:1949)
	at com.suelake.habbo.users.sql.SQLUser.update(SQLUser.java:157)
	at com.blunk.storage.sql.SQLDatabase.update(SQLDatabase.java:101)
	at com.suelake.habbo.users.UserRegister.updateUser(UserRegister.java:129)
	at com.suelake.habbo.communication.requests.UPDATE.handle(UPDATE.java:42)
	at com.suelake.habbo.communication.ClientCommands.handleRequest(ClientCommands.java:360)
	at com.suelake.habbo.communication.ClientRequestHandlerManager.handleRequest(ClientRequestHandlerManager.java:23)
	at com.suelake.habbo.communication.CommunicationHandler.handleIncomingNetworkData(CommunicationHandler.java:113)
	at com.suelake.habbo.net.InfoConnection.run(InfoConnection.java:198)
	at java.lang.Thread.run(Unknown Source)


12/28/11 3:12 PMjava.net.SocketTimeoutException: Read timed out
	at java.net.SocketInputStream.socketRead0(Native Method)
	at java.net.SocketInputStream.read(Unknown Source)
	at java.net.SocketInputStream.read(Unknown Source)
	at sun.nio.cs.StreamDecoder.readBytes(Unknown Source)
	at sun.nio.cs.StreamDecoder.implRead(Unknown Source)
	at sun.nio.cs.StreamDecoder.read(Unknown Source)
	at java.io.InputStreamReader.read(Unknown Source)
	at java.io.BufferedReader.fill(Unknown Source)
	at java.io.BufferedReader.read(Unknown Source)
	at com.suelake.habbo.net.InfoConnection.run(InfoConnection.java:166)
	at java.lang.Thread.run(Unknown Source)


12/28/11 3:12 PMjava.net.SocketTimeoutException: Read timed out
	at java.net.SocketInputStream.socketRead0(Native Method)
	at java.net.SocketInputStream.read(Unknown Source)
	at java.net.SocketInputStream.read(Unknown Source)
	at sun.nio.cs.StreamDecoder.readBytes(Unknown Source)
	at sun.nio.cs.StreamDecoder.implRead(Unknown Source)
	at sun.nio.cs.StreamDecoder.read(Unknown Source)
	at java.io.InputStreamReader.read(Unknown Source)
	at java.io.BufferedReader.fill(Unknown Source)
	at java.io.BufferedReader.read(Unknown Source)
	at com.suelake.habbo.net.InfoConnection.run(InfoConnection.java:166)
	at java.lang.Thread.run(Unknown Source)


12/28/11 3:12 PMjava.net.SocketTimeoutException: Read timed out
	at java.net.SocketInputStream.socketRead0(Native Method)
	at java.net.SocketInputStream.read(Unknown Source)
	at java.net.SocketInputStream.read(Unknown Source)
	at sun.nio.cs.StreamDecoder.readBytes(Unknown Source)
	at sun.nio.cs.StreamDecoder.implRead(Unknown Source)
	at sun.nio.cs.StreamDecoder.read(Unknown Source)
	at java.io.InputStreamReader.read(Unknown Source)
	at java.io.BufferedReader.fill(Unknown Source)
	at java.io.BufferedReader.read(Unknown Source)
	at com.suelake.habbo.net.InfoConnection.run(InfoConnection.java:166)
	at java.lang.Thread.run(Unknown Source)


12/28/11 3:12 PMcom.mysql.jdbc.exceptions.jdbc4.MySQLIntegrityConstraintViolationException: Duplicate entry '143-Chloe' for key 'PRIMARY'
	at sun.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
	at sun.reflect.NativeConstructorAccessorImpl.newInstance(Unknown Source)
	at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(Unknown Source)
	at java.lang.reflect.Constructor.newInstance(Unknown Source)
	at com.mysql.jdbc.Util.handleNewInstance(Util.java:406)
	at com.mysql.jdbc.Util.getInstance(Util.java:381)
	at com.mysql.jdbc.SQLError.createSQLException(SQLError.java:1015)
	at com.mysql.jdbc.SQLError.createSQLException(SQLError.java:956)
	at com.mysql.jdbc.MysqlIO.checkErrorPacket(MysqlIO.java:3515)
	at com.mysql.jdbc.MysqlIO.checkErrorPacket(MysqlIO.java:3447)
	at com.mysql.jdbc.MysqlIO.sendCommand(MysqlIO.java:1951)
	at com.mysql.jdbc.MysqlIO.sqlQueryDirect(MysqlIO.java:2101)
	at com.mysql.jdbc.ConnectionImpl.execSQL(ConnectionImpl.java:2554)
	at com.mysql.jdbc.PreparedStatement.executeInternal(PreparedStatement.java:1761)
	at com.mysql.jdbc.PreparedStatement.executeUpdate(PreparedStatement.java:2046)
	at com.mysql.jdbc.PreparedStatement.executeUpdate(PreparedStatement.java:1964)
	at com.mysql.jdbc.PreparedStatement.executeUpdate(PreparedStatement.java:1949)
	at com.suelake.habbo.users.sql.SQLUser.update(SQLUser.java:157)
	at com.blunk.storage.sql.SQLDatabase.update(SQLDatabase.java:101)
	at com.suelake.habbo.users.UserRegister.updateUser(UserRegister.java:129)
	at com.suelake.habbo.communication.CommunicationHandler.stop(CommunicationHandler.java:178)
	at com.suelake.habbo.net.InfoConnection.sendData(InfoConnection.java:152)
	at com.suelake.habbo.communication.CommunicationHandler.sendMessage(CommunicationHandler.java:213)
	at com.suelake.habbo.communication.CommunicationHandler.systemMsg(CommunicationHandler.java:246)
	at com.suelake.habbo.net.InfoConnection.run(InfoConnection.java:215)
	at java.lang.Thread.run(Unknown Source)


12/28/11 3:12 PMcom.mysql.jdbc.exceptions.jdbc4.MySQLIntegrityConstraintViolationException: Duplicate entry '143-Chloe' for key 'PRIMARY'
	at sun.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
	at sun.reflect.NativeConstructorAccessorImpl.newInstance(Unknown Source)
	at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(Unknown Source)
	at java.lang.reflect.Constructor.newInstance(Unknown Source)
	at com.mysql.jdbc.Util.handleNewInstance(Util.java:406)
	at com.mysql.jdbc.Util.getInstance(Util.java:381)
	at com.mysql.jdbc.SQLError.createSQLException(SQLError.java:1015)
	at com.mysql.jdbc.SQLError.createSQLException(SQLError.java:956)
	at com.mysql.jdbc.MysqlIO.checkErrorPacket(MysqlIO.java:3515)
	at com.mysql.jdbc.MysqlIO.checkErrorPacket(MysqlIO.java:3447)
	at com.mysql.jdbc.MysqlIO.sendCommand(MysqlIO.java:1951)
	at com.mysql.jdbc.MysqlIO.sqlQueryDirect(MysqlIO.java:2101)
	at com.mysql.jdbc.ConnectionImpl.execSQL(ConnectionImpl.java:2554)
	at com.mysql.jdbc.PreparedStatement.executeInternal(PreparedStatement.java:1761)
	at com.mysql.jdbc.PreparedStatement.executeUpdate(PreparedStatement.java:2046)
	at com.mysql.jdbc.PreparedStatement.executeUpdate(PreparedStatement.java:1964)
	at com.mysql.jdbc.PreparedStatement.executeUpdate(PreparedStatement.java:1949)
	at com.suelake.habbo.users.sql.SQLUser.update(SQLUser.java:157)
	at com.blunk.storage.sql.SQLDatabase.update(SQLDatabase.java:101)
	at com.suelake.habbo.users.UserRegister.updateUser(UserRegister.java:129)
	at com.suelake.habbo.communication.CommunicationHandler.stop(CommunicationHandler.java:178)
	at com.suelake.habbo.net.InfoConnection.run(InfoConnection.java:220)
	at java.lang.Thread.run(Unknown Source)


12/28/11 3:16 PMcom.mysql.jdbc.exceptions.jdbc4.MySQLIntegrityConstraintViolationException: Duplicate entry '143-Chloe' for key 'PRIMARY'
	at sun.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
	at sun.reflect.NativeConstructorAccessorImpl.newInstance(Unknown Source)
	at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(Unknown Source)
	at java.lang.reflect.Constructor.newInstance(Unknown Source)
	at com.mysql.jdbc.Util.handleNewInstance(Util.java:406)
	at com.mysql.jdbc.Util.getInstance(Util.java:381)
	at com.mysql.jdbc.SQLError.createSQLException(SQLError.java:1015)
	at com.mysql.jdbc.SQLError.createSQLException(SQLError.java:956)
	at com.mysql.jdbc.MysqlIO.checkErrorPacket(MysqlIO.java:3515)
	at com.mysql.jdbc.MysqlIO.checkErrorPacket(MysqlIO.java:3447)
	at com.mysql.jdbc.MysqlIO.sendCommand(MysqlIO.java:1951)
	at com.mysql.jdbc.MysqlIO.sqlQueryDirect(MysqlIO.java:2101)
	at com.mysql.jdbc.ConnectionImpl.execSQL(ConnectionImpl.java:2554)
	at com.mysql.jdbc.PreparedStatement.executeInternal(PreparedStatement.java:1761)
	at com.mysql.jdbc.PreparedStatement.executeUpdate(PreparedStatement.java:2046)
	at com.mysql.jdbc.PreparedStatement.executeUpdate(PreparedStatement.java:1964)
	at com.mysql.jdbc.PreparedStatement.executeUpdate(PreparedStatement.java:1949)
	at com.suelake.habbo.users.sql.SQLUser.update(SQLUser.java:157)
	at com.blunk.storage.sql.SQLDatabase.update(SQLDatabase.java:101)
	at com.suelake.habbo.users.UserRegister.updateUser(UserRegister.java:129)
	at com.suelake.habbo.communication.CommunicationHandler.login(CommunicationHandler.java:324)
	at com.suelake.habbo.communication.requests.LOGIN.handle(LOGIN.java:16)
	at com.suelake.habbo.communication.ClientCommands.handleRequest(ClientCommands.java:360)
	at com.suelake.habbo.communication.ClientRequestHandlerManager.handleRequest(ClientRequestHandlerManager.java:23)
	at com.suelake.habbo.communication.CommunicationHandler.handleIncomingNetworkData(CommunicationHandler.java:113)
	at com.suelake.habbo.net.InfoConnection.run(InfoConnection.java:198)
	at java.lang.Thread.run(Unknown Source)


12/28/11 3:18 PMcom.mysql.jdbc.exceptions.jdbc4.MySQLIntegrityConstraintViolationException: Duplicate entry '143-Chloe' for key 'PRIMARY'
	at sun.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
	at sun.reflect.NativeConstructorAccessorImpl.newInstance(Unknown Source)
	at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(Unknown Source)
	at java.lang.reflect.Constructor.newInstance(Unknown Source)
	at com.mysql.jdbc.Util.handleNewInstance(Util.java:406)
	at com.mysql.jdbc.Util.getInstance(Util.java:381)
	at com.mysql.jdbc.SQLError.createSQLException(SQLError.java:1015)
	at com.mysql.jdbc.SQLError.createSQLException(SQLError.java:956)
	at com.mysql.jdbc.MysqlIO.checkErrorPacket(MysqlIO.java:3515)
	at com.mysql.jdbc.MysqlIO.checkErrorPacket(MysqlIO.java:3447)
	at com.mysql.jdbc.MysqlIO.sendCommand(MysqlIO.java:1951)
	at com.mysql.jdbc.MysqlIO.sqlQueryDirect(MysqlIO.java:2101)
	at com.mysql.jdbc.ConnectionImpl.execSQL(ConnectionImpl.java:2554)
	at com.mysql.jdbc.PreparedStatement.executeInternal(PreparedStatement.java:1761)
	at com.mysql.jdbc.PreparedStatement.executeUpdate(PreparedStatement.java:2046)
	at com.mysql.jdbc.PreparedStatement.executeUpdate(PreparedStatement.java:1964)
	at com.mysql.jdbc.PreparedStatement.executeUpdate(PreparedStatement.java:1949)
	at com.suelake.habbo.users.sql.SQLUser.update(SQLUser.java:157)
	at com.blunk.storage.sql.SQLDatabase.update(SQLDatabase.java:101)
	at com.suelake.habbo.users.UserRegister.updateUser(UserRegister.java:129)
	at com.suelake.habbo.communication.requests.BTCKS.handle(BTCKS.java:52)
	at com.suelake.habbo.communication.ClientCommands.handleRequest(ClientCommands.java:360)
	at com.suelake.habbo.communication.ClientRequestHandlerManager.handleRequest(ClientRequestHandlerManager.java:23)
	at com.suelake.habbo.communication.CommunicationHandler.handleIncomingNetworkData(CommunicationHandler.java:113)
	at com.suelake.habbo.net.InfoConnection.run(InfoConnection.java:198)
	at java.lang.Thread.run(Unknown Source)


12/28/11 3:20 PMcom.mysql.jdbc.exceptions.jdbc4.MySQLIntegrityConstraintViolationException: Duplicate entry '143-Chloe' for key 'PRIMARY'
	at sun.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
	at sun.reflect.NativeConstructorAccessorImpl.newInstance(Unknown Source)
	at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(Unknown Source)
	at java.lang.reflect.Constructor.newInstance(Unknown Source)
	at com.mysql.jdbc.Util.handleNewInstance(Util.java:406)
	at com.mysql.jdbc.Util.getInstance(Util.java:381)
	at com.mysql.jdbc.SQLError.createSQLException(SQLError.java:1015)
	at com.mysql.jdbc.SQLError.createSQLException(SQLError.java:956)
	at com.mysql.jdbc.MysqlIO.checkErrorPacket(MysqlIO.java:3515)
	at com.mysql.jdbc.MysqlIO.checkErrorPacket(MysqlIO.java:3447)
	at com.mysql.jdbc.MysqlIO.sendCommand(MysqlIO.java:1951)
	at com.mysql.jdbc.MysqlIO.sqlQueryDirect(MysqlIO.java:2101)
	at com.mysql.jdbc.ConnectionImpl.execSQL(ConnectionImpl.java:2554)
	at com.mysql.jdbc.PreparedStatement.executeInternal(PreparedStatement.java:1761)
	at com.mysql.jdbc.PreparedStatement.executeUpdate(PreparedStatement.java:2046)
	at com.mysql.jdbc.PreparedStatement.executeUpdate(PreparedStatement.java:1964)
	at com.mysql.jdbc.PreparedStatement.executeUpdate(PreparedStatement.java:1949)
	at com.suelake.habbo.users.sql.SQLUser.update(SQLUser.java:157)
	at com.blunk.storage.sql.SQLDatabase.update(SQLDatabase.java:101)
	at com.suelake.habbo.users.UserRegister.updateUser(UserRegister.java:129)
	at com.suelake.habbo.communication.CommunicationHandler.stop(CommunicationHandler.java:178)
	at com.suelake.habbo.communication.ClientManager.disconnectUser(ClientManager.java:217)
	at com.suelake.habbo.communication.CommunicationHandler.login(CommunicationHandler.java:307)
	at com.suelake.habbo.communication.requests.LOGIN.handle(LOGIN.java:16)
	at com.suelake.habbo.communication.ClientCommands.handleRequest(ClientCommands.java:360)
	at com.suelake.habbo.communication.ClientRequestHandlerManager.handleRequest(ClientRequestHandlerManager.java:23)
	at com.suelake.habbo.communication.CommunicationHandler.handleIncomingNetworkData(CommunicationHandler.java:113)
	at com.suelake.habbo.net.InfoConnection.run(InfoConnection.java:198)
	at java.lang.Thread.run(Unknown Source)


12/28/11 3:20 PMcom.mysql.jdbc.exceptions.jdbc4.MySQLIntegrityConstraintViolationException: Duplicate entry '143-Chloe' for key 'PRIMARY'
	at sun.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
	at sun.reflect.NativeConstructorAccessorImpl.newInstance(Unknown Source)
	at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(Unknown Source)
	at java.lang.reflect.Constructor.newInstance(Unknown Source)
	at com.mysql.jdbc.Util.handleNewInstance(Util.java:406)
	at com.mysql.jdbc.Util.getInstance(Util.java:381)
	at com.mysql.jdbc.SQLError.createSQLException(SQLError.java:1015)
	at com.mysql.jdbc.SQLError.createSQLException(SQLError.java:956)
	at com.mysql.jdbc.MysqlIO.checkErrorPacket(MysqlIO.java:3515)
	at com.mysql.jdbc.MysqlIO.checkErrorPacket(MysqlIO.java:3447)
	at com.mysql.jdbc.MysqlIO.sendCommand(MysqlIO.java:1951)
	at com.mysql.jdbc.MysqlIO.sqlQueryDirect(MysqlIO.java:2101)
	at com.mysql.jdbc.ConnectionImpl.execSQL(ConnectionImpl.java:2554)
	at com.mysql.jdbc.PreparedStatement.executeInternal(PreparedStatement.java:1761)
	at com.mysql.jdbc.PreparedStatement.executeUpdate(PreparedStatement.java:2046)
	at com.mysql.jdbc.PreparedStatement.executeUpdate(PreparedStatement.java:1964)
	at com.mysql.jdbc.PreparedStatement.executeUpdate(PreparedStatement.java:1949)
	at com.suelake.habbo.users.sql.SQLUser.update(SQLUser.java:157)
	at com.blunk.storage.sql.SQLDatabase.update(SQLDatabase.java:101)
	at com.suelake.habbo.users.UserRegister.updateUser(UserRegister.java:129)
	at com.suelake.habbo.communication.CommunicationHandler.stop(CommunicationHandler.java:178)
	at com.suelake.habbo.net.InfoConnection.run(InfoConnection.java:220)
	at java.lang.Thread.run(Unknown Source)


12/28/11 3:23 PMcom.mysql.jdbc.exceptions.jdbc4.MySQLIntegrityConstraintViolationException: Duplicate entry '143-iAubree' for key 'PRIMARY'
	at sun.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
	at sun.reflect.NativeConstructorAccessorImpl.newInstance(Unknown Source)
	at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(Unknown Source)
	at java.lang.reflect.Constructor.newInstance(Unknown Source)
	at com.mysql.jdbc.Util.handleNewInstance(Util.java:406)
	at com.mysql.jdbc.Util.getInstance(Util.java:381)
	at com.mysql.jdbc.SQLError.createSQLException(SQLError.java:1015)
	at com.mysql.jdbc.SQLError.createSQLException(SQLError.java:956)
	at com.mysql.jdbc.MysqlIO.checkErrorPacket(MysqlIO.java:3515)
	at com.mysql.jdbc.MysqlIO.checkErrorPacket(MysqlIO.java:3447)
	at com.mysql.jdbc.MysqlIO.sendCommand(MysqlIO.java:1951)
	at com.mysql.jdbc.MysqlIO.sqlQueryDirect(MysqlIO.java:2101)
	at com.mysql.jdbc.ConnectionImpl.execSQL(ConnectionImpl.java:2554)
	at com.mysql.jdbc.PreparedStatement.executeInternal(PreparedStatement.java:1761)
	at com.mysql.jdbc.PreparedStatement.executeUpdate(PreparedStatement.java:2046)
	at com.mysql.jdbc.PreparedStatement.executeUpdate(PreparedStatement.java:1964)
	at com.mysql.jdbc.PreparedStatement.executeUpdate(PreparedStatement.java:1949)
	at com.suelake.habbo.users.sql.SQLUser.update(SQLUser.java:157)
	at com.blunk.storage.sql.SQLDatabase.update(SQLDatabase.java:101)
	at com.suelake.habbo.users.UserRegister.updateUser(UserRegister.java:129)
	at com.suelake.habbo.communication.CommunicationHandler.stop(CommunicationHandler.java:178)
	at com.suelake.habbo.net.InfoConnection.run(InfoConnection.java:220)
	at java.lang.Thread.run(Unknown Source)


12/28/11 8:24 PMjava.net.SocketTimeoutException: Read timed out
	at java.net.SocketInputStream.socketRead0(Native Method)
	at java.net.SocketInputStream.read(Unknown Source)
	at java.net.SocketInputStream.read(Unknown Source)
	at sun.nio.cs.StreamDecoder.readBytes(Unknown Source)
	at sun.nio.cs.StreamDecoder.implRead(Unknown Source)
	at sun.nio.cs.StreamDecoder.read(Unknown Source)
	at java.io.InputStreamReader.read(Unknown Source)
	at java.io.BufferedReader.fill(Unknown Source)
	at java.io.BufferedReader.read(Unknown Source)
	at com.suelake.habbo.net.InfoConnection.run(InfoConnection.java:166)
	at java.lang.Thread.run(Unknown Source)


